name: Smoke2 (reusable)
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      zap_enabled:
        required: false
        default: true
        type: boolean
    secrets:
      DOCKERHUB_USERNAME:
        required: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SMOKE OK — imagen ${{ inputs.image_name }}"
      - if: ${{ inputs.zap_enabled }}
        run: echo "ZAP enabled"
